title: Solutions in software engineering
description: Knowledgebase and solutions for devs
author: Alexander Schreiner
github: https://github.com/alexander-schreiner
about: Software Engineer

enableTags: true
tagarray: [ ]

collections:
  blog:
    output: true
    permalink: /blog/:path/

social:
  - icon: fa-linkedin
    link: "https://www.linkedin.com/in/alexander-schreiner-5722721b6/"
  - icon: fa-stack-exchange
    link: "#"
  - icon: fa-github
    link: "https://github.com/alexander-schreiner"

urls:
  - text: About Me
    url: /about/
  - text: Sitemap
    url: /sitemap.xml

url: "https://alexander-schreiner.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/blog/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: [ "<!-- ", " -->" ]
  endings: all
  ignore:
    envs: [ 'development' ]
